# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adad0592bcdea40d91ad84ccd15682e70104f0e33f12688cc6104fb59a2a4ea48e1dc64dd52cd37b26d282aa99d6c26616b5ffd4baa5a45b9b51fe5263a0cd9e

test:
  secret_key_base: 8e14a209b222be074de4e4148256f2d7d17bbc112cb55a6ac7bb06f396ff284ffb9f7bcd2f503d281ffc1e4b1893e171a066c9bcbcfd16489f4474823c1adb42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
